version: 2

sources:
  - name: raw_data
    schema: "{{ 'tpc_raw' if target.type in ('spark', 'databricks') else 'raw' }}"
    database: "{{ 'dev' if target.type == 'duckdb' else '' }}"
    tables:
      - name: call_center
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 6
      - name: catalog_page
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 11718
      - name: catalog_returns
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 144067
      - name: catalog_sales
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 1441548
      - name: customer
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 100000
      - name: customer_address
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 50000
      - name: customer_demographics
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 1920800
      - name: date_dim
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 73049
      - name: dbgen_version
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 1
      - name: household_demographics
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 7200
      - name: income_band
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 20
      - name: inventory
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 11745000
      - name: item
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 18000
      - name: promotion
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 300
      - name: reason
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 75
      - name: ship_mode
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 20
      - name: store
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 12
      - name: store_returns
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 287514
      - name: store_sales
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 2880404
      - name: time_dim
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 86400
      - name: warehouse
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 5
      - name: web_page
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 60
      - name: web_returns
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 71763
      - name: web_sales
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 719384
      - name: web_site
        data_tests:
          - expect_row_count_1:
              arguments:
                row_count_1: 30
